# Generated by Django 4.2.5 on 2023-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalAPI', '0002_cartmodel_categorymodel_menuitemmodel_orderitemmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
